import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { ShelfLifeReplenishmentService } from '../src/domain.mjs';
import { buildReplenishmentPlan } from '../src/policy.mjs';
import { AtomicStore } from '../src/store.mjs';
import { MemoryStore, planner, replenishment } from './helpers.mjs';

describe('ShelfLifeReplenishmentService', () => {
  it('calculates usable stock, expiry exposure, replenishment target, and eligible supplier lines', () => { const plan = buildReplenishmentPlan(replenishment); expect(plan).toMatchObject({ useBeforeDays: 10, usableUnits: 130, expiryRiskUnits: 30, leadDemandUnits: 60, targetStockUnits: 240, projectedUnitsAtArrival: 70, recommendedOrderUnits: 170, estimatedOrderCost: 850, fullySourced: true, exceptionReasons: ['on_hand_expiry_risk'] }); expect(plan.orderLines).toEqual([{ supplierId: 'SUP-A', supplierName: 'Fresh Supply', orderedUnits: 170, unitCost: 5, leadDays: 2, lineCost: 850 }]); expect(plan.exclusions).toEqual([{ supplierId: 'SUP-C', reason: 'lead_time_exceeded' }, { supplierId: 'SUP-D', reason: 'shelf_life_insufficient' }]); });
  it('routes expiry-risk stock to exception authority and permits planner revision', () => { const service = new ShelfLifeReplenishmentService(new MemoryStore()); let record = service.create(replenishment, planner, 'create-871'); record = service.transition(record.id, 'calculatePlan', { note: 'expiry-aware calculation' }, planner, 'calculate-871'); expect(record.status).toBe('exception_required'); record = service.transition(record.id, 'approveException', { note: 'expiry action approved' }, { id: 'authority-871', role: 'inventory_expiry_authority' }, 'exception-871'); expect(record.status).toBe('exception_approved'); });
  it('records a standard reviewed, approved, and released replenishment plan', () => { const clean = { ...replenishment, onHandBatches: [{ batchId: 'B-1', units: 100, daysToExpiry: 20 }] }; const store = new MemoryStore(); const service = new ShelfLifeReplenishmentService(store); let record = service.create(clean, planner, 'standard-create-871'); record = service.transition(record.id, 'calculatePlan', { note: 'standard calculation' }, planner, 'standard-calculate-871'); record = service.transition(record.id, 'reviewPlan', { note: 'plan reviewed' }, { id: 'reviewer-871', role: 'inventory_replenishment_reviewer' }, 'standard-review-871'); record = service.transition(record.id, 'approvePlan', { note: 'plan approved' }, { id: 'approver-871', role: 'inventory_replenishment_authority' }, 'standard-approve-871'); record = service.transition(record.id, 'releaseOrder', { note: 'order released' }, { id: 'registrar-871', role: 'inventory_order_registrar' }, 'standard-release-871'); expect(record.status).toBe('released'); expect(store.writes).toBe(5); });
  it('rejects invalid batches, replayed identifiers, unauthorized actors, and terminal retries', () => { const service = new ShelfLifeReplenishmentService(new MemoryStore()); expect(() => service.create({ ...replenishment, onHandBatches: [] }, planner, 'invalid-871')).toThrow('one through one hundred inventory batches are required'); let record = service.create({ ...replenishment, onHandBatches: [{ batchId: 'B-1', units: 100, daysToExpiry: 20 }] }, planner, 'unique-871'); expect(() => service.create(replenishment, planner, 'unique-871')).toThrow('request identifier was already used'); expect(() => service.transition(record.id, 'calculatePlan', { note: 'wrong role' }, { id: 'reviewer', role: 'inventory_replenishment_reviewer' }, 'role-871')).toThrow('role inventory_planner is required'); record = service.transition(record.id, 'calculatePlan', { note: 'plan' }, planner, 'plan-871'); record = service.transition(record.id, 'reviewPlan', { note: 'review' }, { id: 'reviewer', role: 'inventory_replenishment_reviewer' }, 'review-871'); record = service.transition(record.id, 'approvePlan', { note: 'approve' }, { id: 'authority', role: 'inventory_replenishment_authority' }, 'approve-871'); record = service.transition(record.id, 'releaseOrder', { note: 'release' }, { id: 'registrar', role: 'inventory_order_registrar' }, 'release-871'); expect(() => service.transition(record.id, 'releaseOrder', { note: 'repeat' }, { id: 'registrar', role: 'inventory_order_registrar' }, 'terminal-871')).toThrow('replenishment request must be approved'); });
  it('recovers an absent replenishment request data file', () => { const directory = mkdtempSync(join(tmpdir(), 'replenishment-request-')); try { const store = new AtomicStore(join(directory, 'data', 'replenishment-requests.json')); expect(store.read()).toEqual({ replenishmentRequests: [] }); } finally { rmSync(directory, { recursive: true, force: true }); } });
});
