import { conflict, forbidden, missing } from './errors.mjs';
import { replenishmentInput, text } from './validation.mjs';
import { buildReplenishmentPlan } from './policy.mjs';
const transitions = { reviewPlan: { from: 'planned', to: 'reviewed', role: 'inventory_replenishment_reviewer', event: 'replenishment_plan_reviewed' }, approvePlan: { from: 'reviewed', to: 'approved', role: 'inventory_replenishment_authority', event: 'replenishment_plan_approved' }, releaseOrder: { from: 'approved', to: 'released', role: 'inventory_order_registrar', event: 'replenishment_order_released' }, approveException: { from: 'exception_required', to: 'exception_approved', role: 'inventory_expiry_authority', event: 'replenishment_exception_approved' } };
const now = () => new Date().toISOString(); const requireRole = (currentActor, requiredRole) => { if (!currentActor?.id || currentActor.role !== requiredRole) throw forbidden(`role ${requiredRole} is required`); }; const requestSeen = (database, requestId) => database.replenishmentRequests.some((request) => request.events.some((entry) => entry.requestId === requestId)); const event = (type, currentActor, requestId, at, note, detail = {}) => ({ type, actorId: currentActor.id, requestId, at, note, ...detail });
export class ShelfLifeReplenishmentService {
  constructor(store) { this.store = store; }
  create(input, currentActor, requestId) { requireRole(currentActor, 'inventory_planner'); const database = this.store.read(); if (requestSeen(database, requestId)) throw conflict('request identifier was already used'); const request = replenishmentInput(input); const at = now(); const record = { id: crypto.randomUUID(), ...request, status: 'draft', replenishmentPlan: null, createdAt: at, updatedAt: at, events: [event('replenishment_request_created', currentActor, requestId, at)] }; database.replenishmentRequests.push(record); this.store.write(database); return record; }
  transition(id, action, input, currentActor, requestId) { const database = this.store.read(); const record = database.replenishmentRequests.find((request) => request.id === id); if (!record) throw missing('replenishment request was not found'); if (requestSeen(database, requestId)) throw conflict('request identifier was already used'); if (action === 'calculatePlan') return this.calculate(record, input, currentActor, requestId, database); if (action === 'reviseRequest') return this.revise(record, input, currentActor, requestId, database); const policy = transitions[action]; if (!policy) throw missing('action was not found'); requireRole(currentActor, policy.role); if (record.status !== policy.from) throw conflict(`replenishment request must be ${policy.from}`); const at = now(); record.status = policy.to; record.updatedAt = at; record.events.push(event(policy.event, currentActor, requestId, at, text(input.note, 'note'))); this.persist(database); return record; }
  calculate(record, input, currentActor, requestId, database) { requireRole(currentActor, 'inventory_planner'); if (record.status !== 'draft') throw conflict('replenishment request must be draft'); const at = now(); record.replenishmentPlan = buildReplenishmentPlan(record); record.status = record.replenishmentPlan.fullySourced && record.replenishmentPlan.exceptionReasons.length === 0 ? 'planned' : 'exception_required'; record.updatedAt = at; record.events.push(event('replenishment_plan_calculated', currentActor, requestId, at, text(input.note, 'note'), { outcome: record.status, recommendedOrderUnits: record.replenishmentPlan.recommendedOrderUnits, estimatedOrderCost: record.replenishmentPlan.estimatedOrderCost })); this.persist(database); return record; }
  revise(record, input, currentActor, requestId, database) { requireRole(currentActor, 'inventory_planner'); if (!['reviewed', 'exception_required'].includes(record.status)) throw conflict('replenishment request must be reviewed or exception_required'); const replacement = replenishmentInput(input); const at = now(); Object.assign(record, replacement, { status: 'draft', replenishmentPlan: null, updatedAt: at }); record.events.push(event('replenishment_request_revised', currentActor, requestId, at, text(input.note, 'note'))); this.persist(database); return record; }
  persist(database) { this.store.write({ replenishmentRequests: database.replenishmentRequests }); }
  get(id) { const record = this.store.read().replenishmentRequests.find((request) => request.id === id); if (!record) throw missing('replenishment request was not found'); return record; }
}
